# --- CONFIG ---
STEP_SIZE = 0.15
STEP_PER_DIRECTION = 3
OBJECTIVE_CORRELATION_WEIGHT = 0.5
OBJECTIVE_SPREAD_WEIGHT = 0.5
CORRELATION_THRESHOLD = 0.1  # adjust as needed
COMPOSITE_SCORE_THRESHOLD = 0.02  # adjust as needed
MAX_ITERATIONS = 3
BUCKET_SIZE = 2
